import type { RouteDir } from '../grammar/tree';

/**
 * The generator writes the route table and the type wiring so an application
 * never hand-writes either. What it emits is ordinary source using the
 * router's public API — readable in a diff, and identical to what someone
 * would have written by hand from the same directories.
 *
 * The shape is built once, generically over what a route file resolves to:
 * identifiers when emitting source, components when a test wants to hand the
 * result to the real `defineRoutes`. One structure, so the thing under test
 * is the thing that ships.
 */

export type TableBranch<T> = {
  layout?: T;
  children: Record<string, TableNode<T>>;
};

export type TableNode<T> = T | TableBranch<T>;

/** A directory with nothing but a page is the component itself. */
const isLeaf = (dir: RouteDir): boolean =>
  dir.page !== null &&
  dir.layout === null &&
  dir.notFound === null &&
  dir.children.length === 0;

/**
 * Literal segments before parameters, and otherwise the order the directories
 * came in. The table matches in declaration order, and the directories arrive
 * sorted by name — under which `[slug]` precedes `about`, because `[` sorts
 * before letters. Left alone, the most ordinary layout there is would make
 * `/about` unreachable behind `/:slug`.
 *
 * A directory tree has no order of its own to honour, so the framework has to
 * choose one; this is the only choice that makes every declared route
 * reachable.
 */
const order = (children: readonly RouteDir[]): readonly RouteDir[] => [
  ...children.filter((child) => child.kind !== 'param'),
  ...children.filter((child) => child.kind === 'param'),
];

export const buildTable = <T>(
  tree: RouteDir,
  resolve: (file: string) => T,
): Record<string, TableNode<T>> => {
  const entries = (dir: RouteDir): Record<string, TableNode<T>> => {
    const record: Record<string, TableNode<T>> = {};
    if (dir.page !== null) record['/'] = resolve(dir.page);
    for (const child of order(dir.children)) record[child.key] = node(child);
    // Last, because the table matches in declaration order: every route the
    // app actually declared out-ranks the catch-all.
    if (dir.notFound !== null) record['/*'] = resolve(dir.notFound);
    return record;
  };

  const node = (dir: RouteDir): TableNode<T> => {
    if (isLeaf(dir)) return resolve(dir.page as string);
    const branch: TableBranch<T> = { children: entries(dir) };
    if (dir.layout !== null) branch.layout = resolve(dir.layout);
    return branch;
  };

  // The root's own layout has to wrap everything, which is what a branch
  // under the transparent '/' key does.
  return tree.layout === null ? entries(tree) : { '/': node(tree) };
};

export type EmitOptions = {
  /** Import specifier prefix for the route files, e.g. `./routes`. */
  readonly importPrefix: string;
};

const BANNER =
  '// Generated by @k8ordo/framework-engine from routes/. Do not edit.';

const sanitize = (path: string): string => {
  const base = path
    .replace(/\.[jt]sx?$/u, '')
    .replaceAll(/[^A-Za-z0-9]+/gu, '_')
    .replaceAll(/^_+|_+$/gu, '');
  return base === '' ? 'route' : base;
};

const createNamer = (): {
  names: Map<string, string>;
  take: (f: string) => string;
} => {
  const names = new Map<string, string>();
  const used = new Set<string>();
  return {
    names,
    take: (file) => {
      const existing = names.get(file);
      if (existing !== undefined) return existing;
      const base = sanitize(file);
      let name = base;
      for (let n = 2; used.has(name); n += 1) name = `${base}_${n}`;
      used.add(name);
      names.set(file, name);
      return name;
    },
  };
};

const pad = (depth: number): string => '  '.repeat(depth);

const isBranch = (node: TableNode<string>): node is TableBranch<string> =>
  typeof node !== 'string';

const renderNode = (node: TableNode<string>, depth: number): string => {
  if (!isBranch(node)) return node;
  const lines = ['{'];
  if (node.layout !== undefined) {
    lines.push(`${pad(depth + 1)}layout: ${node.layout},`);
  }
  lines.push(`${pad(depth + 1)}children: {`);
  for (const [key, child] of Object.entries(node.children)) {
    lines.push(`${pad(depth + 2)}'${key}': ${renderNode(child, depth + 2)},`);
  }
  lines.push(`${pad(depth + 1)}},`, `${pad(depth)}}`);
  return lines.join('\n');
};

export const emitRoutesModule = (
  tree: RouteDir,
  options: EmitOptions,
): string => {
  const namer = createNamer();
  const table = buildTable(tree, namer.take);

  const body = Object.entries(table).map(
    ([key, node]) => `${pad(1)}'${key}': ${renderNode(node, 1)},`,
  );
  const importLines = [...namer.names].map(
    ([file, name]) =>
      `import ${name} from '${options.importPrefix}/${file.replace(/\.[jt]sx?$/u, '')}';`,
  );

  return [
    BANNER,
    '',
    `import { defineRoutes } from '@k8ordo/router';`,
    '',
    ...importLines,
    '',
    'export const routes = defineRoutes({',
    ...body,
    '});',
    '',
  ].join('\n');
};

export type RegisterOptions = {
  /** Import specifier of the generated routes module, e.g. `./routes.gen`. */
  readonly routesModule: string;
  /** Present only when the application depends on `@k8ordo/state`. */
  readonly stateModule?: string | null;
};

/**
 * Both packages read the app's route table through declaration merging, so
 * the app gets typed paths everywhere without writing the ceremony itself.
 */
export const emitRegisterModule = (options: RegisterOptions): string => {
  const lines = [
    BANNER,
    '',
    `import type { RouteOf } from '@k8ordo/router';`,
    `import type { routes } from '${options.routesModule}';`,
    '',
    `declare module '@k8ordo/router' {`,
    '  interface Register {',
    '    routes: typeof routes;',
    '  }',
    '}',
  ];
  if (options.stateModule !== null && options.stateModule !== undefined) {
    lines.push(
      '',
      `declare module '${options.stateModule}' {`,
      '  interface Register {',
      '    path: RouteOf<typeof routes>;',
      '  }',
      '}',
    );
  }
  lines.push(
    '',
    '// The RSC plugin resolves these specifiers itself — nothing to install.',
    '// Declared here so importing one is not a type error.',
    "declare module 'server-only' {}",
    "declare module 'client-only' {}",
    '',
  );
  return lines.join('\n');
};
