import { fileURLToPath } from 'node:url';

import { fmt, react, tailwind, test } from '@k8o/oxc-config';
import { defineConfig } from 'vite-plus';

// oxlint-tailwindcss v1 resolves `entryPoint` relative to oxlint's working
// directory (each package dir under `vp run -r check`), so absolute paths
// resolved from this config keep it portable across packages and machines.
const cssEntry = (path: string) =>
  fileURLToPath(new URL(path, import.meta.url));

// oxlint-tailwindcss 1.6.0 は `--value(integer)` の関数型 @utility
// (grid-cols-auto-fit-* 等) をクラス一覧に列挙できず、no-unknown-classes が
// 実際にはコンパイルされるクラスを誤検知する。1.7.1 で修正済みのため
// (sergioazoc/oxlint-tailwindcss#104)、更新を取り込んだらこの除外を消す。
const noUnknownClassesOptions = {
  ignorePrefixes: [
    'grid-cols-auto-fill-',
    'grid-cols-auto-fit-',
    'grid-rows-auto-fill-',
    'grid-rows-auto-fit-',
  ],
};

export default defineConfig({
  fmt: {
    ...fmt,
    // index.css は手書きの単一ソース (CSS として管理、oxfmt 対象外)。
    // tokens.generated.ts は tailwind-token-extractor の出力なので生成器の整形を維持する
    // (oxfmt で再整形すると `check:tokens` がドリフト判定になるため)。
    ignorePatterns: [
      'CHANGELOG.md',
      '.claude/**',
      // ledger.yaml 等は pnpm リリース管理が生成・所有するファイルなので整形規則を当てない
      '.changeset/**',
      'packages/ui/src/styles/index.css',
      'packages/ui/src/styles/tokens.generated.ts',
      // Build artifact generated by apps/docs/scripts/generate-design-md.ts
      // (gitignored); never format the locally-built copy.
      'apps/docs/public/design.md',
    ],
  },
  lint: {
    extends: [react, tailwind],
    ignorePatterns: [
      'CHANGELOG.md',
      '.claude/**',
      // pnpm リリース管理が生成・所有するファイル (ledger.yaml 等)
      '.changeset/**',
      // Generated by tailwind-token-extractor; not hand-maintained.
      '**/tokens.generated.ts',
      // CI用スクリプト。tsconfig外の .mjs のため型情報前提のルールが誤検知する
      '.github/scripts/**',
    ],
    options: {
      reportUnusedDisableDirectives: 'error',
    },
    rules: {
      // 非セマンティック要素への意図的な role 付与を許容する。
      // avatar/code の role="img" は子要素を持つラッパー (img タグ化は不可)、
      // progress の role="progressbar" はスタイル付き div、separator は span 設計。
      'jsx-a11y/prefer-tag-over-role': 'off',
      // type="text" の input は combobox/spinbutton の暗黙 role を持たないため、
      // autocomplete/number-field の明示 role は冗長ではない (ルールの誤検知)。
      'jsx-a11y/no-redundant-roles': 'off',
      // listbox/option など ARIA 複合ウィジェットでは ul/li に widget role を
      // 付与するのが正規パターン (標準 eslint-plugin-jsx-a11y も許容)。
      // oxlint は過剰に検出するため無効化。
      'jsx-a11y/no-noninteractive-element-to-interactive-role': 'off',
      // ErrorBoundary の fallbackRender などレンダープロップを許容する
      // (コンポーネント定義ではなく描画関数。実コンポーネントの入れ子定義は引き続き検出)。
      'react/no-unstable-nested-components': ['error', { allowAsProps: true }],
      'tailwindcss/no-unknown-classes': ['warn', noUnknownClassesOptions],
    },
    settings: {
      react: { version: '19.2.5' },
      // oxlint-tailwindcss v1 は明示的な Tailwind エントリポイントが必須。
      // @k8ordo/ui は src/styles/index.css が単一ソース。docs / examples は
      // それを取り込んだ各自の globals.css を使う。
      tailwindcss: {
        entryPoint: [
          {
            files: '**/apps/docs/**',
            use: cssEntry('./apps/docs/src/styles/globals.css'),
          },
          {
            files: '**/examples/nextjs/**',
            use: cssEntry('./examples/nextjs/src/app/globals.css'),
          },
          {
            files: '**',
            use: cssEntry('./packages/ui/src/styles/index.css'),
          },
        ],
      },
    },
    overrides: [
      {
        // 上の settings.tailwindcss.entryPoint のグロブは oxlint の実行 CWD
        // からの相対パスにマッチするため、`vp run -r check` (CWD=各パッケージ)
        // では docs のファイルが `src/...` となりマッピングに一致せず、
        // fallback の @k8ordo/ui index.css で検証されて docs 固有の
        // ユーティリティ (font-palt / break-phrase / bg-preview-bg) が誤検知
        // される。ルールオプションの entryPoint は settings より優先されるので
        // ここで明示する (vp の overrides グロブはルート相対で解決される)。
        files: ['apps/docs/**'],
        rules: {
          'tailwindcss/no-unknown-classes': [
            'warn',
            {
              entryPoint: cssEntry('./apps/docs/src/styles/globals.css'),
              ...noUnknownClassesOptions,
            },
          ],
        },
      },
      {
        files: ['**/*.test.ts', '**/*.test.tsx'],
        plugins: [...(test.plugins ?? [])],
        rules: test.rules,
      },
      {
        // Storybook stories と config は test 同等の relax + Storybook パターン特有の緩和
        files: ['**/*.stories.{ts,tsx}', '**/.storybook/**/*.{ts,tsx}'],
        rules: {
          'no-console': 'off',
          'jest/no-conditional-in-test': 'off',
          'typescript/strict-void-return': 'off',
          'typescript/no-floating-promises': 'off',
          'typescript/no-misused-promises': 'off',
          'typescript/no-non-null-assertion': 'off',
          'typescript/no-unsafe-assignment': 'off',
        },
      },
    ],
  },
  staged: {
    '*.{js,ts,cjs,mjs,jsx,tsx,json,jsonc}': 'vp check --fix',
  },
});
