/**
 * Generates `apps/docs/public/llms.txt` — the LLM-facing docs index served at
 * `https://ordo.k8o.me/llms.txt`.
 *
 * Single source of truth:
 *   packages/ui/docs/llms.txt ──(this)──► public/llms.txt
 *
 * The npm-shipped index links to files inside the package
 * (`node_modules/@k8ordo/ui/docs/`). This script rewrites those
 * package-relative links to URLs that resolve on the docs site, and fails on
 * any link it does not know how to map so new docs force a mapping decision.
 *
 *   node scripts/generate-llms-txt.ts            # write public/llms.txt
 *   node scripts/generate-llms-txt.ts --check    # fail if the file is stale
 */
import { readFile, writeFile } from 'node:fs/promises';
import { fileURLToPath } from 'node:url';

const SRC_PATH = fileURLToPath(
  new URL('../../../packages/ui/docs/llms.txt', import.meta.url),
);
const OUT_PATH = fileURLToPath(new URL('../public/llms.txt', import.meta.url));

const SITE_URL = 'https://ordo.k8o.me';

/**
 * Package-relative link → docs-site URL. The four design references all map to
 * `/design.md` because that single generated file carries their site version.
 */
const LINK_MAP: Record<string, string> = {
  'GUIDE.md': `${SITE_URL}/docs/GUIDE.md`,
  'references/components.md': `${SITE_URL}/docs/references/components.md`,
  'references/ai-chat.md': `${SITE_URL}/docs/references/ai-chat.md`,
  'references/generative-ui.md': `${SITE_URL}/docs/references/generative-ui.md`,
  'references/typography.md': `${SITE_URL}/docs/references/typography.md`,
  'references/color.md': `${SITE_URL}/docs/references/color.md`,
  'references/spatial-design.md': `${SITE_URL}/docs/references/spatial-design.md`,
  'references/interaction-design.md': `${SITE_URL}/docs/references/interaction-design.md`,
  'references/hooks.md': `${SITE_URL}/docs/references/hooks.md`,
  'references/helpers.md': `${SITE_URL}/docs/references/helpers.md`,
};

/** npm-specific orientation paragraph, replaced by a site-specific one. */
const NPM_NOTE = `When installed via npm, these docs live under \`node_modules/@k8ordo/ui/docs/\`.
Start with GUIDE.md, then follow the reference most relevant to the task.`;
const SITE_NOTE = `These docs are served from <${SITE_URL}>.
Start with the Design Guide, then follow the reference most relevant to the task.`;

const HEADER = `<!-- AUTO-GENERATED by apps/docs/scripts/generate-llms-txt.ts — DO NOT EDIT BY HAND.
     Source: packages/ui/docs/llms.txt (links rewritten to site URLs).
     Regenerate: pnpm --filter docs generate:llms -->

`;

function build(source: string): string {
  if (!source.includes(NPM_NOTE)) {
    throw new Error(
      'llms.txt: npm note paragraph not found in source — update generate-llms-txt.ts',
    );
  }
  const rewritten = source
    .replace(NPM_NOTE, SITE_NOTE)
    .replaceAll(/\]\(([^)]+)\)/gu, (match, target: string) => {
      if (/^https?:/u.test(target)) return match;
      const mapped = LINK_MAP[target];
      if (mapped === undefined) {
        throw new Error(
          `llms.txt: no site URL mapping for link "${target}" — update generate-llms-txt.ts`,
        );
      }
      return `](${mapped})`;
    });
  return `${HEADER}${rewritten}`;
}

// ── entry ───────────────────────────────────────────────────────────────────

const txt = build(await readFile(SRC_PATH, 'utf8'));

if (process.argv.includes('--check')) {
  const current = await readFile(OUT_PATH, 'utf8').catch(() => '');
  if (current !== txt) {
    process.stderr.write(
      'llms.txt is out of sync with packages/ui/docs/llms.txt.\n' +
        'Fix with: pnpm --filter docs generate:llms\n',
    );
    process.exit(1);
  }
  process.stdout.write('llms.txt is in sync.\n');
} else {
  await writeFile(OUT_PATH, txt);
  process.stdout.write(`Wrote ${OUT_PATH}\n`);
}
