// AUTO-GENERATED by tailwind-token-extractor. DO NOT EDIT BY HAND.
// Re-run the extractor to update.

export const tokens = {
  theme: {
    animate: {
      spin: 'spin 1s linear infinite',
      ping: 'ping 1s cubic-bezier(0, 0, 0.2, 1) infinite',
      pulse: 'pulse 2s cubic-bezier(0.4, 0, 0.6, 1) infinite',
      bounce: 'bounce 1s infinite',
    },
    aspect: {
      video: '16 / 9',
    },
    blur: {
      xs: '4px',
      sm: '8px',
      md: '12px',
      lg: '16px',
      xl: '24px',
      '2xl': '40px',
      '3xl': '64px',
      DEFAULT: '8px',
    },
    breakpoint: {
      sm: '40rem',
      md: '48rem',
      lg: '64rem',
      xl: '80rem',
      '2xl': '96rem',
    },
    color: {
      'fg-base': {
        light: 'oklch(0.25 0.0015 235)',
        dark: 'oklch(0.975 0.001 235)',
      },
      'fg-subtle': {
        light: 'oklch(0.52 0.006 235)',
        dark: 'oklch(0.75 0.005 235)',
      },
      'fg-mute': {
        light: 'oklch(0.42 0.003 235)',
        dark: 'oklch(0.84 0.004 235)',
      },
      'fg-inverse': {
        light: 'oklch(0.975 0.001 235)',
        dark: 'oklch(0.25 0.0015 235)',
      },
      'fg-info': {
        light: 'oklch(0.41 0.215 260)',
        dark: 'oklch(0.9 0.078 260)',
      },
      'fg-success': {
        light: 'oklch(0.41 0.14 150)',
        dark: 'oklch(0.9 0.1 150)',
      },
      'fg-warning': {
        light: 'oklch(0.41 0.11 90)',
        dark: 'oklch(0.9 0.148 90)',
      },
      'fg-error': {
        light: 'oklch(0.41 0.18 25)',
        dark: 'oklch(0.9 0.084 25)',
      },
      'bg-base': {
        light: 'oklch(1 0 0)',
        dark: 'oklch(0.3 0.002 235)',
      },
      'bg-raised': {
        light: 'oklch(1 0 0)',
        dark: 'oklch(0.3 0.002 235)',
      },
      'bg-surface': {
        light: 'oklch(0.975 0.001 235)',
        dark: 'oklch(0.18 0.001 235)',
      },
      'bg-subtle': {
        light: 'oklch(0.955 0.0015 235)',
        dark: 'oklch(0.25 0.0015 235)',
      },
      'bg-mute': {
        light: 'oklch(0.925 0.003 235)',
        dark: 'oklch(0.42 0.003 235)',
      },
      'bg-emphasize': {
        light: 'oklch(0.84 0.004 235)',
        dark: 'oklch(0.52 0.006 235)',
      },
      'bg-inverse': {
        light: 'oklch(0.25 0.0015 235)',
        dark: 'oklch(1 0 0)',
      },
      'bg-info': {
        light: 'oklch(0.945 0.04 260)',
        dark: 'oklch(0.37 0.165 260)',
      },
      'bg-success': {
        light: 'oklch(0.945 0.052 150)',
        dark: 'oklch(0.37 0.108 150)',
      },
      'bg-warning': {
        light: 'oklch(0.945 0.08 90)',
        dark: 'oklch(0.37 0.085 90)',
      },
      'bg-error': {
        light: 'oklch(0.945 0.042 25)',
        dark: 'oklch(0.37 0.14 25)',
      },
      'border-base': {
        light: 'oklch(0.75 0.005 235)',
        dark: 'oklch(0.52 0.006 235)',
      },
      'border-subtle': {
        light: 'oklch(0.955 0.0015 235)',
        dark: 'oklch(0.42 0.003 235)',
      },
      'border-mute': {
        light: 'oklch(0.925 0.003 235)',
        dark: 'oklch(0.52 0.006 235)',
      },
      'border-emphasize': 'oklch(0.66 0.006 235)',
      'border-inverse': {
        light: 'oklch(0.42 0.003 235)',
        dark: 'oklch(0.84 0.004 235)',
      },
      'border-info': {
        light: 'oklch(0.66 0.255 260)',
        dark: 'oklch(0.75 0.21 260)',
      },
      'border-success': {
        light: 'oklch(0.66 0.245 150)',
        dark: 'oklch(0.75 0.235 150)',
      },
      'border-warning': {
        light: 'oklch(0.66 0.18 90)',
        dark: 'oklch(0.75 0.2 90)',
      },
      'border-error': {
        light: 'oklch(0.66 0.27 25)',
        dark: 'oklch(0.75 0.225 25)',
      },
      'primary-fg': {
        light: 'oklch(0.41 0.098 180)',
        dark: 'oklch(0.84 0.16 180)',
      },
      'primary-bg': {
        light: 'oklch(0.9 0.11 180)',
        dark: 'oklch(0.41 0.098 180)',
      },
      'primary-bg-subtle': {
        light: 'oklch(0.975 0.02 180)',
        dark: 'oklch(0.18 0.055 180)',
      },
      'primary-bg-mute': {
        light: 'oklch(0.955 0.042 180)',
        dark: 'oklch(0.37 0.078 180)',
      },
      'primary-bg-emphasize': {
        light: 'oklch(0.84 0.16 180)',
        dark: 'oklch(0.49 0.12 180)',
      },
      'primary-border': 'oklch(0.66 0.165 180)',
      'secondary-fg': {
        light: 'oklch(0.41 0.105 210)',
        dark: 'oklch(0.84 0.155 210)',
      },
      'secondary-bg': {
        light: 'oklch(0.9 0.098 210)',
        dark: 'oklch(0.41 0.105 210)',
      },
      'secondary-bg-subtle': {
        light: 'oklch(0.975 0.022 210)',
        dark: 'oklch(0.18 0.058 210)',
      },
      'secondary-bg-mute': {
        light: 'oklch(0.955 0.04 210)',
        dark: 'oklch(0.37 0.082 210)',
      },
      'secondary-bg-emphasize': {
        light: 'oklch(0.84 0.155 210)',
        dark: 'oklch(0.49 0.128 210)',
      },
      'secondary-border': 'oklch(0.66 0.17 210)',
      transparent: 'transparent',
      'back-drop': 'rgb(0, 0, 0, 0.5)',
      'group-primary': {
        light: 'oklch(0.41 0.098 180)',
        dark: 'oklch(0.9 0.11 180)',
      },
      'group-secondary': {
        light: 'oklch(0.41 0.105 210)',
        dark: 'oklch(0.9 0.098 210)',
      },
      'group-tertiary': {
        light: 'oklch(0.41 0.19 350)',
        dark: 'oklch(0.9 0.078 350)',
      },
      'group-quaternary': {
        light: 'oklch(0.41 0.22 305)',
        dark: 'oklch(0.9 0.082 305)',
      },
    },
    container: {
      '3xs': '16rem',
      '2xs': '18rem',
      xs: '20rem',
      sm: '24rem',
      md: '28rem',
      lg: '32rem',
      xl: '36rem',
      '2xl': '42rem',
      '3xl': '48rem',
      '4xl': '56rem',
      '5xl': '64rem',
      '6xl': '72rem',
      '7xl': '80rem',
    },
    default: {
      'transition-duration': '150ms',
      'transition-timing-function': 'cubic-bezier(0.4, 0, 0.2, 1)',
      'font-family': '--theme(--font-sans, initial)',
      'font-feature-settings': '--theme(\n      --font-sans--font-feature-settings,\n      initial\n    )',
      'font-variation-settings': '--theme(\n      --font-sans--font-variation-settings,\n      initial\n    )',
      'mono-font-family': '--theme(--font-mono, initial)',
      'mono-font-feature-settings': '--theme(\n      --font-mono--font-feature-settings,\n      initial\n    )',
      'mono-font-variation-settings': '--theme(\n      --font-mono--font-variation-settings,\n      initial\n    )',
    },
    'drop-shadow': {
      xs: '0 1px 1px rgb(0 0 0 / 0.05)',
      sm: '0 1px 2px rgb(0 0 0 / 0.15)',
      md: '0 3px 3px rgb(0 0 0 / 0.12)',
      lg: '0 4px 4px rgb(0 0 0 / 0.15)',
      xl: '0 9px 7px rgb(0 0 0 / 0.1)',
      '2xl': '0 25px 25px rgb(0 0 0 / 0.15)',
      DEFAULT: '0 1px 2px rgb(0 0 0 / 0.1), 0 1px 1px rgb(0 0 0 / 0.06)',
    },
    ease: {
      in: 'cubic-bezier(0.4, 0, 1, 1)',
      out: 'cubic-bezier(0, 0, 0.2, 1)',
      'in-out': 'cubic-bezier(0.4, 0, 0.2, 1)',
    },
    font: {
      'noto-sans-jp': 'var(--font-noto-sans-jp)',
      'm-plus-2': 'var(--font-m-plus-2)',
    },
    'font-weight': {
      medium: 450,
      bold: 700,
    },
    'inset-shadow': {
      '2xs': 'inset 0 1px rgb(0 0 0 / 0.05)',
      xs: 'inset 0 1px 1px rgb(0 0 0 / 0.05)',
      sm: 'inset 0 2px 4px rgb(0 0 0 / 0.05)',
    },
    leading: {
      none: 1,
      tight: 1.25,
      snug: 1.375,
      normal: 1.5,
      relaxed: 1.625,
      loose: 2,
    },
    'max-width': {
      prose: '65ch',
    },
    perspective: {
      dramatic: '100px',
      near: '300px',
      normal: '500px',
      midrange: '800px',
      distant: '1200px',
    },
    radius: {
      xs: '0.125rem',
      sm: '0.375rem',
      md: '0.5rem',
      lg: '0.75rem',
      xl: '1rem',
      '2xl': '1.25rem',
    },
    shadow: {
      '2xs': '0 1px rgb(0 0 0 / 0.05)',
      xs: '0 1px 2px 0 rgb(0 0 0 / 0.05)',
      sm: '0 1px 3px 0 rgb(0 0 0 / 0.1), 0 1px 2px -1px rgb(0 0 0 / 0.1)',
      md: '0 4px 6px -1px rgb(0 0 0 / 0.1), 0 2px 4px -2px rgb(0 0 0 / 0.1)',
      lg: '0 10px 15px -3px rgb(0 0 0 / 0.1), 0 4px 6px -4px rgb(0 0 0 / 0.1)',
      xl: '0 20px 25px -5px rgb(0 0 0 / 0.1), 0 8px 10px -6px rgb(0 0 0 / 0.1)',
      '2xl': '0 25px 50px -12px rgb(0 0 0 / 0.25)',
    },
    spacing: '0.25rem',
    text: {
      xs: {
        value: '0.75rem',
        lineHeight: 'calc(1 / 0.75)',
        lineHeightNumber: 1.333333,
      },
      sm: {
        value: '0.875rem',
        lineHeight: 'calc(1.25 / 0.875)',
        lineHeightNumber: 1.428571,
      },
      md: {
        value: '1rem',
        lineHeight: 'calc(1.5 / 1)',
        lineHeightNumber: 1.5,
      },
      lg: {
        value: '1.125rem',
        lineHeight: 'calc(1.75 / 1.125)',
        lineHeightNumber: 1.555556,
      },
      xl: {
        value: '1.25rem',
        lineHeight: 'calc(1.75 / 1.25)',
        lineHeightNumber: 1.4,
      },
      '2xl': {
        value: '1.5rem',
        lineHeight: 'calc(2 / 1.5)',
        lineHeightNumber: 1.333333,
      },
      '3xl': {
        value: '1.875rem',
        lineHeight: 'calc(2.25 / 1.875)',
        lineHeightNumber: 1.2,
      },
      emphasize: {
        value: '3rem',
        lineHeight: 1,
        lineHeightNumber: 1,
      },
      highlight: {
        value: '6rem',
        lineHeight: 1,
        lineHeightNumber: 1,
      },
    },
    'text-shadow': {
      '2xs': '0px 1px 0px rgb(0 0 0 / 0.15)',
      xs: '0px 1px 1px rgb(0 0 0 / 0.2)',
      sm: '0px 1px 0px rgb(0 0 0 / 0.075), 0px 1px 1px rgb(0 0 0 / 0.075),\n      0px 2px 2px rgb(0 0 0 / 0.075)',
      md: '0px 1px 1px rgb(0 0 0 / 0.1), 0px 1px 2px rgb(0 0 0 / 0.1),\n      0px 2px 4px rgb(0 0 0 / 0.1)',
      lg: '0px 1px 2px rgb(0 0 0 / 0.1), 0px 3px 2px rgb(0 0 0 / 0.1),\n      0px 4px 8px rgb(0 0 0 / 0.1)',
    },
    tracking: {
      none: '0em',
      normal: '0.025em',
    },
  },
  vars: {
    white: 'oklch(1 0 0)',
    'gray-50': 'oklch(0.975 0.001 235)',
    'gray-100': 'oklch(0.955 0.0015 235)',
    'gray-200': 'oklch(0.925 0.003 235)',
    'gray-300': 'oklch(0.84 0.004 235)',
    'gray-400': 'oklch(0.75 0.005 235)',
    'gray-500': 'oklch(0.66 0.006 235)',
    'gray-600': 'oklch(0.52 0.006 235)',
    'gray-700': 'oklch(0.42 0.003 235)',
    'gray-800': 'oklch(0.3 0.002 235)',
    'gray-900': 'oklch(0.25 0.0015 235)',
    'gray-950': 'oklch(0.18 0.001 235)',
    'red-50': 'oklch(0.975 0.016 25)',
    'red-100': 'oklch(0.945 0.042 25)',
    'red-200': 'oklch(0.9 0.084 25)',
    'red-300': 'oklch(0.84 0.15 25)',
    'red-400': 'oklch(0.75 0.225 25)',
    'red-500': 'oklch(0.66 0.27 25)',
    'red-600': 'oklch(0.575 0.255 25)',
    'red-700': 'oklch(0.49 0.22 25)',
    'red-800': 'oklch(0.41 0.18 25)',
    'red-900': 'oklch(0.37 0.14 25)',
    'red-950': 'oklch(0.18 0.1 25)',
    'pink-50': 'oklch(0.975 0.016 350)',
    'pink-100': 'oklch(0.945 0.038 350)',
    'pink-200': 'oklch(0.9 0.078 350)',
    'pink-300': 'oklch(0.84 0.145 350)',
    'pink-400': 'oklch(0.75 0.225 350)',
    'pink-500': 'oklch(0.66 0.27 350)',
    'pink-600': 'oklch(0.575 0.26 350)',
    'pink-700': 'oklch(0.49 0.23 350)',
    'pink-800': 'oklch(0.41 0.19 350)',
    'pink-900': 'oklch(0.37 0.15 350)',
    'pink-950': 'oklch(0.18 0.108 350)',
    'purple-50': 'oklch(0.975 0.018 305)',
    'purple-100': 'oklch(0.945 0.042 305)',
    'purple-200': 'oklch(0.9 0.082 305)',
    'purple-300': 'oklch(0.84 0.155 305)',
    'purple-400': 'oklch(0.75 0.24 305)',
    'purple-500': 'oklch(0.66 0.29 305)',
    'purple-600': 'oklch(0.575 0.295 305)',
    'purple-700': 'oklch(0.49 0.265 305)',
    'purple-800': 'oklch(0.41 0.22 305)',
    'purple-900': 'oklch(0.37 0.175 305)',
    'purple-950': 'oklch(0.18 0.125 305)',
    'cyan-50': 'oklch(0.975 0.022 210)',
    'cyan-100': 'oklch(0.955 0.04 210)',
    'cyan-200': 'oklch(0.9 0.098 210)',
    'cyan-300': 'oklch(0.84 0.155 210)',
    'cyan-400': 'oklch(0.75 0.18 210)',
    'cyan-500': 'oklch(0.66 0.17 210)',
    'cyan-600': 'oklch(0.575 0.15 210)',
    'cyan-700': 'oklch(0.49 0.128 210)',
    'cyan-800': 'oklch(0.41 0.105 210)',
    'cyan-900': 'oklch(0.37 0.082 210)',
    'cyan-950': 'oklch(0.18 0.058 210)',
    'blue-50': 'oklch(0.975 0.016 260)',
    'blue-100': 'oklch(0.945 0.04 260)',
    'blue-200': 'oklch(0.9 0.078 260)',
    'blue-300': 'oklch(0.84 0.145 260)',
    'blue-400': 'oklch(0.75 0.21 260)',
    'blue-500': 'oklch(0.66 0.255 260)',
    'blue-600': 'oklch(0.575 0.275 260)',
    'blue-700': 'oklch(0.49 0.26 260)',
    'blue-800': 'oklch(0.41 0.215 260)',
    'blue-900': 'oklch(0.37 0.165 260)',
    'blue-950': 'oklch(0.18 0.118 260)',
    'teal-50': 'oklch(0.975 0.02 180)',
    'teal-100': 'oklch(0.955 0.042 180)',
    'teal-200': 'oklch(0.9 0.11 180)',
    'teal-300': 'oklch(0.84 0.16 180)',
    'teal-400': 'oklch(0.75 0.175 180)',
    'teal-500': 'oklch(0.66 0.165 180)',
    'teal-600': 'oklch(0.575 0.145 180)',
    'teal-700': 'oklch(0.49 0.12 180)',
    'teal-800': 'oklch(0.41 0.098 180)',
    'teal-900': 'oklch(0.37 0.078 180)',
    'teal-950': 'oklch(0.18 0.055 180)',
    'green-50': 'oklch(0.975 0.02 150)',
    'green-100': 'oklch(0.945 0.052 150)',
    'green-200': 'oklch(0.9 0.1 150)',
    'green-300': 'oklch(0.84 0.175 150)',
    'green-400': 'oklch(0.75 0.235 150)',
    'green-500': 'oklch(0.66 0.245 150)',
    'green-600': 'oklch(0.575 0.22 150)',
    'green-700': 'oklch(0.49 0.18 150)',
    'green-800': 'oklch(0.41 0.14 150)',
    'green-900': 'oklch(0.37 0.108 150)',
    'green-950': 'oklch(0.18 0.075 150)',
    'yellow-50': 'oklch(0.975 0.03 90)',
    'yellow-100': 'oklch(0.945 0.08 90)',
    'yellow-200': 'oklch(0.9 0.148 90)',
    'yellow-300': 'oklch(0.84 0.2 90)',
    'yellow-400': 'oklch(0.75 0.2 90)',
    'yellow-500': 'oklch(0.66 0.18 90)',
    'yellow-600': 'oklch(0.575 0.158 90)',
    'yellow-700': 'oklch(0.49 0.135 90)',
    'yellow-800': 'oklch(0.41 0.11 90)',
    'yellow-900': 'oklch(0.37 0.085 90)',
    'yellow-950': 'oklch(0.18 0.06 90)',
    'orange-50': 'oklch(0.975 0.02 55)',
    'orange-100': 'oklch(0.945 0.05 55)',
    'orange-200': 'oklch(0.9 0.098 55)',
    'orange-300': 'oklch(0.84 0.165 55)',
    'orange-400': 'oklch(0.75 0.22 55)',
    'orange-500': 'oklch(0.66 0.24 55)',
    'orange-600': 'oklch(0.575 0.235 55)',
    'orange-700': 'oklch(0.49 0.2 55)',
    'orange-800': 'oklch(0.41 0.165 55)',
    'orange-900': 'oklch(0.37 0.128 55)',
    'orange-950': 'oklch(0.18 0.09 55)',
    'fg-base': {
      light: 'oklch(0.25 0.0015 235)',
      dark: 'oklch(0.975 0.001 235)',
    },
    'fg-subtle': {
      light: 'oklch(0.52 0.006 235)',
      dark: 'oklch(0.75 0.005 235)',
    },
    'fg-mute': {
      light: 'oklch(0.42 0.003 235)',
      dark: 'oklch(0.84 0.004 235)',
    },
    'fg-inverse': {
      light: 'oklch(0.975 0.001 235)',
      dark: 'oklch(0.25 0.0015 235)',
    },
    'fg-info': {
      light: 'oklch(0.41 0.215 260)',
      dark: 'oklch(0.9 0.078 260)',
    },
    'fg-success': {
      light: 'oklch(0.41 0.14 150)',
      dark: 'oklch(0.9 0.1 150)',
    },
    'fg-warning': {
      light: 'oklch(0.41 0.11 90)',
      dark: 'oklch(0.9 0.148 90)',
    },
    'fg-error': {
      light: 'oklch(0.41 0.18 25)',
      dark: 'oklch(0.9 0.084 25)',
    },
    'bg-base': {
      light: 'oklch(1 0 0)',
      dark: 'oklch(0.3 0.002 235)',
    },
    'bg-raised': {
      light: 'oklch(1 0 0)',
      dark: 'oklch(0.3 0.002 235)',
    },
    'bg-surface': {
      light: 'oklch(0.975 0.001 235)',
      dark: 'oklch(0.18 0.001 235)',
    },
    'bg-subtle': {
      light: 'oklch(0.955 0.0015 235)',
      dark: 'oklch(0.25 0.0015 235)',
    },
    'bg-mute': {
      light: 'oklch(0.925 0.003 235)',
      dark: 'oklch(0.42 0.003 235)',
    },
    'bg-emphasize': {
      light: 'oklch(0.84 0.004 235)',
      dark: 'oklch(0.52 0.006 235)',
    },
    'bg-inverse': {
      light: 'oklch(0.25 0.0015 235)',
      dark: 'oklch(1 0 0)',
    },
    'bg-info': {
      light: 'oklch(0.945 0.04 260)',
      dark: 'oklch(0.37 0.165 260)',
    },
    'bg-success': {
      light: 'oklch(0.945 0.052 150)',
      dark: 'oklch(0.37 0.108 150)',
    },
    'bg-warning': {
      light: 'oklch(0.945 0.08 90)',
      dark: 'oklch(0.37 0.085 90)',
    },
    'bg-error': {
      light: 'oklch(0.945 0.042 25)',
      dark: 'oklch(0.37 0.14 25)',
    },
    'border-base': {
      light: 'oklch(0.75 0.005 235)',
      dark: 'oklch(0.52 0.006 235)',
    },
    'border-subtle': {
      light: 'oklch(0.955 0.0015 235)',
      dark: 'oklch(0.42 0.003 235)',
    },
    'border-mute': {
      light: 'oklch(0.925 0.003 235)',
      dark: 'oklch(0.52 0.006 235)',
    },
    'border-emphasize': 'oklch(0.66 0.006 235)',
    'border-inverse': {
      light: 'oklch(0.42 0.003 235)',
      dark: 'oklch(0.84 0.004 235)',
    },
    'border-info': {
      light: 'oklch(0.66 0.255 260)',
      dark: 'oklch(0.75 0.21 260)',
    },
    'border-success': {
      light: 'oklch(0.66 0.245 150)',
      dark: 'oklch(0.75 0.235 150)',
    },
    'border-warning': {
      light: 'oklch(0.66 0.18 90)',
      dark: 'oklch(0.75 0.2 90)',
    },
    'border-error': {
      light: 'oklch(0.66 0.27 25)',
      dark: 'oklch(0.75 0.225 25)',
    },
    'primary-fg': {
      light: 'oklch(0.41 0.098 180)',
      dark: 'oklch(0.84 0.16 180)',
    },
    'primary-bg': {
      light: 'oklch(0.9 0.11 180)',
      dark: 'oklch(0.41 0.098 180)',
    },
    'primary-bg-subtle': {
      light: 'oklch(0.975 0.02 180)',
      dark: 'oklch(0.18 0.055 180)',
    },
    'primary-bg-mute': {
      light: 'oklch(0.955 0.042 180)',
      dark: 'oklch(0.37 0.078 180)',
    },
    'primary-bg-emphasize': {
      light: 'oklch(0.84 0.16 180)',
      dark: 'oklch(0.49 0.12 180)',
    },
    'primary-border': 'oklch(0.66 0.165 180)',
    'secondary-fg': {
      light: 'oklch(0.41 0.105 210)',
      dark: 'oklch(0.84 0.155 210)',
    },
    'secondary-bg': {
      light: 'oklch(0.9 0.098 210)',
      dark: 'oklch(0.41 0.105 210)',
    },
    'secondary-bg-subtle': {
      light: 'oklch(0.975 0.022 210)',
      dark: 'oklch(0.18 0.058 210)',
    },
    'secondary-bg-mute': {
      light: 'oklch(0.955 0.04 210)',
      dark: 'oklch(0.37 0.082 210)',
    },
    'secondary-bg-emphasize': {
      light: 'oklch(0.84 0.155 210)',
      dark: 'oklch(0.49 0.128 210)',
    },
    'secondary-border': 'oklch(0.66 0.17 210)',
    'back-drop': 'rgb(0, 0, 0, 0.5)',
    'z-overlay': 1000,
    'z-modal': 1300,
    'z-toast': 1500,
    'group-primary': {
      light: 'oklch(0.41 0.098 180)',
      dark: 'oklch(0.9 0.11 180)',
    },
    'group-secondary': {
      light: 'oklch(0.41 0.105 210)',
      dark: 'oklch(0.9 0.098 210)',
    },
    'group-tertiary': {
      light: 'oklch(0.41 0.19 350)',
      dark: 'oklch(0.9 0.078 350)',
    },
    'group-quaternary': {
      light: 'oklch(0.41 0.22 305)',
      dark: 'oklch(0.9 0.082 305)',
    },
  },
  refs: {
    'fg-base': {
      light: 'gray-900',
      dark: 'gray-50',
    },
    'fg-subtle': {
      light: 'gray-600',
      dark: 'gray-400',
    },
    'fg-mute': {
      light: 'gray-700',
      dark: 'gray-300',
    },
    'fg-inverse': {
      light: 'gray-50',
      dark: 'gray-900',
    },
    'fg-info': {
      light: 'blue-800',
      dark: 'blue-200',
    },
    'fg-success': {
      light: 'green-800',
      dark: 'green-200',
    },
    'fg-warning': {
      light: 'yellow-800',
      dark: 'yellow-200',
    },
    'fg-error': {
      light: 'red-800',
      dark: 'red-200',
    },
    'bg-base': {
      light: 'white',
      dark: 'gray-800',
    },
    'bg-raised': {
      light: 'white',
      dark: 'gray-800',
    },
    'bg-surface': {
      light: 'gray-50',
      dark: 'gray-950',
    },
    'bg-subtle': {
      light: 'gray-100',
      dark: 'gray-900',
    },
    'bg-mute': {
      light: 'gray-200',
      dark: 'gray-700',
    },
    'bg-emphasize': {
      light: 'gray-300',
      dark: 'gray-600',
    },
    'bg-inverse': {
      light: 'gray-900',
      dark: 'white',
    },
    'bg-info': {
      light: 'blue-100',
      dark: 'blue-900',
    },
    'bg-success': {
      light: 'green-100',
      dark: 'green-900',
    },
    'bg-warning': {
      light: 'yellow-100',
      dark: 'yellow-900',
    },
    'bg-error': {
      light: 'red-100',
      dark: 'red-900',
    },
    'border-base': {
      light: 'gray-400',
      dark: 'gray-600',
    },
    'border-subtle': {
      light: 'gray-100',
      dark: 'gray-700',
    },
    'border-mute': {
      light: 'gray-200',
      dark: 'gray-600',
    },
    'border-emphasize': {
      light: 'gray-500',
      dark: 'gray-500',
    },
    'border-inverse': {
      light: 'gray-700',
      dark: 'gray-300',
    },
    'border-info': {
      light: 'blue-500',
      dark: 'blue-400',
    },
    'border-success': {
      light: 'green-500',
      dark: 'green-400',
    },
    'border-warning': {
      light: 'yellow-500',
      dark: 'yellow-400',
    },
    'border-error': {
      light: 'red-500',
      dark: 'red-400',
    },
    'primary-fg': {
      light: 'teal-800',
      dark: 'teal-300',
    },
    'primary-bg': {
      light: 'teal-200',
      dark: 'teal-800',
    },
    'primary-bg-subtle': {
      light: 'teal-50',
      dark: 'teal-950',
    },
    'primary-bg-mute': {
      light: 'teal-100',
      dark: 'teal-900',
    },
    'primary-bg-emphasize': {
      light: 'teal-300',
      dark: 'teal-700',
    },
    'primary-border': {
      light: 'teal-500',
      dark: 'teal-500',
    },
    'secondary-fg': {
      light: 'cyan-800',
      dark: 'cyan-300',
    },
    'secondary-bg': {
      light: 'cyan-200',
      dark: 'cyan-800',
    },
    'secondary-bg-subtle': {
      light: 'cyan-50',
      dark: 'cyan-950',
    },
    'secondary-bg-mute': {
      light: 'cyan-100',
      dark: 'cyan-900',
    },
    'secondary-bg-emphasize': {
      light: 'cyan-300',
      dark: 'cyan-700',
    },
    'secondary-border': {
      light: 'cyan-500',
      dark: 'cyan-500',
    },
    'group-primary': {
      light: 'teal-800',
      dark: 'teal-200',
    },
    'group-secondary': {
      light: 'cyan-800',
      dark: 'cyan-200',
    },
    'group-tertiary': {
      light: 'pink-800',
      dark: 'pink-200',
    },
    'group-quaternary': {
      light: 'purple-800',
      dark: 'purple-200',
    },
  },
} as const;

export const meta = {
  source: 'src/styles/index.css',
  tailwindVersion: '4.3.3',
  unresolved: [
    '--font-noto-sans-jp',
    '--font-m-plus-2',
  ],
} as const;

export type ThemeNamespace = keyof typeof tokens.theme;
export type VarName = keyof typeof tokens.vars;
export type RefName = keyof typeof tokens.refs;
export type AnimateToken = keyof typeof tokens.theme.animate;
export type AspectToken = keyof typeof tokens.theme.aspect;
export type BlurToken = keyof typeof tokens.theme.blur;
export type BreakpointToken = keyof typeof tokens.theme.breakpoint;
export type ColorToken = keyof typeof tokens.theme.color;
export type ContainerToken = keyof typeof tokens.theme.container;
export type DefaultToken = keyof typeof tokens.theme.default;
export type DropShadowToken = keyof typeof tokens.theme['drop-shadow'];
export type EaseToken = keyof typeof tokens.theme.ease;
export type FontToken = keyof typeof tokens.theme.font;
export type FontWeightToken = keyof typeof tokens.theme['font-weight'];
export type InsetShadowToken = keyof typeof tokens.theme['inset-shadow'];
export type LeadingToken = keyof typeof tokens.theme.leading;
export type MaxWidthToken = keyof typeof tokens.theme['max-width'];
export type PerspectiveToken = keyof typeof tokens.theme.perspective;
export type RadiusToken = keyof typeof tokens.theme.radius;
export type ShadowToken = keyof typeof tokens.theme.shadow;
export type TextToken = keyof typeof tokens.theme.text;
export type TextShadowToken = keyof typeof tokens.theme['text-shadow'];
export type TrackingToken = keyof typeof tokens.theme.tracking;
